# [[language]]
# name = "latex"


# [language.config.texlab.build]
# executable = "tectonic"
# args = ["-X", "compile", "%f", "--synctex", "--keep-logs", "--keep-intermediates"]
# onSave = true 
# forwardSearchAfter = true

# [language.config.texlab.forwardSearch]
# executable = "zathura"
# args = [ "--synctex-forward", "%l:1:%f", "%p" ]

# [language.config.texlab.chktex]
# onEdit = true

[[language]]
name = "svelte"
language-servers = [ "tailwindcss-svelte", "svelteserver" ]

[language-server.tailwindcss-svelte]
language-id = "svelte"
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { }

[[language]]
name = "css"
language-servers = [ "tailwindcss-css", "vscode-css-language-server" ]

[language-server.tailwindcss-css]
language-id = "css"
command = "tailwindcss-language-server"
args = ["-v", "--stdio"]
config = { }

[[language]]
name = "html"
language-servers = [ "tailwindcss-html", "vscode-html-language-server" ]

[language-server.tailwindcss-html]
language-id = "html"
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { }
