[language-server.elm-language-server]
command = "node"
args = ["/home/gaby/src/elm-language-server/out/node/index.js"]
[language-server.elm-language-server.config.elmLS]
elmReviewDiagnostics = "warning"
elmReviewPath = "/home/gaby/.nix-profile/bin/elm-review"

[[language]]
name = "perl"
file-types = ["pm", "t"]

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { run = "onSave" } }

[language-server.jdtls]
command = "jdt-language-server"
